### ISSUE TITLE
fabric 1.14.3 crash on load server

### ISSUE THREAD

**Issue by SDUBZ** [MrMarnic/AnimalNet#12]
[crash-2019-07-01_15.22.47-server.txt](https://github.com/MrMarnic/AnimalNet/files/3344033/crash-2019-07-01_15.22.47-server.txt)

animal net version: AnimalNet-1.9+Fabric+1.14.2
fabric 1.14.3
fabric api: fabric-api-0.3.0+build.187

**Comment by MrMarnic** [comment]
you should use v1.14.3 Fabric b1
