### ISSUE TITLE
Small compatibility issue with another mod.

### ISSUE THREAD

**Issue by calloatti** [MrMarnic/AnimalNet#14]
When used with this mod that enables spawners to be picked up with silk touch: 

https://www.curseforge.com/minecraft/mc-mods/silky-spawners

When you break a spawner, you get the spawner and some spawner shards, that way you can get  unlimited spawner shards by just placing and breaking the same spawner.

Fabric 1.14.3
AnimalNet-v1.14.3 Fabric b3
Silky-Spawners-1.0.2

**Comment by MrMarnic** [comment]
I will see what I can do.

**Comment by MrMarnic** [comment]
It is fixed.
