### ISSUE TITLE
Tick Crash

### ISSUE THREAD

**Issue by JustJinxed** [MrMarnic/AnimalNet#16]
Not so sure about this one... May or not be you, considering how many mods I have going since updating the Fabric API/Cotton suite. But figure you should at least be aware of the odd interaction. 

https://pastebin.com/gd0MgCY9

**Comment by MrMarnic** [comment]
which fabric vesion are you using?

**Comment by calloatti** [comment]
I think this is the same problem: 

https://paste.ee/p/GfTP2

fabric-api-0.3.0+build.207.jar

This must be an interaction with another mod, since I am using Animal Net in another modpack with no crashes

**Comment by MrMarnic** [comment]
Can you tell me which mods you are using?

**Comment by MrMarnic** [comment]
I am going to close this because of no further info
