### ISSUE TITLE
[1.14.4] server crash forge

### ISSUE THREAD

**Issue by Sunekaer** [MrMarnic/AnimalNet#17]
Server crash on launch 
forge:28.0.38
animalnet-v1.14.4 Forge b3.jar
https://paste.dimdev.org/elececejuf.rb

**Comment by MrMarnic** [comment]
Did you change something in the config?

**Comment by MrMarnic** [comment]
Can you post you config please

**Comment by Sunekaer** [comment]
Default config
https://s1.sunekaer.com/files/animalnet-common.toml

**Comment by MrMarnic** [comment]
Can you please tell me how you got the error. Because I can not reproduce it.
I think it has something to do with the config. Did you try to delete the animalnet config file?

**Comment by Sunekaer** [comment]
Well, i downloaded forge server and copied all mods over and launched the server.
It generated config files it self

**Comment by MrMarnic** [comment]
Does the mod work alone?

**Comment by MrMarnic** [comment]
I am going to close this because of no further info
