### ISSUE TITLE
1.14.4(fabric) crash on world gen(animalnet-v1.14.4+Fabric+b2)

### ISSUE THREAD

**Issue by SDUBZ** [MrMarnic/AnimalNet#18]
crash report:
[crash-2019-08-08_03.21.28-server.txt](https://github.com/MrMarnic/AnimalNet/files/3478203/crash-2019-08-08_03.21.28-server.txt)
log:
[latest.log](https://github.com/MrMarnic/AnimalNet/files/3478207/latest.log)

**Comment by MrMarnic** [comment]
Does the mod work if you only have installed it?

**Comment by SDUBZ** [comment]
it works now since the update

**Comment by MrMarnic** [comment]
That’s great. So I can close this?
