### ISSUE TITLE
Fabric mixin incompablity.

### ISSUE THREAD

**Issue by modmuss50** [MrMarnic/AnimalNet#19]
Hello! I had an issue posted on my issue tracker about RebornCore being incompatible with AnimalNet.

https://github.com/TechReborn/RebornCore/issues/119

After looking at your mixin `AnimalNetMixinCrafting` you are using `@Overwrite`. This replaces the whole method and makes it impossible for other mixins to inject into it thus casuing a crash with reborn core.

It seems like  you are trying to achieve something very similar to what I have in Reborn Core.

https://github.com/TechReborn/RebornCore/blob/1.14/src/main/java/reborncore/mixin/common/MixinCraftingResultSlot.java#L41-L44

Above I have linked to an example of using `@Inject` to inject after the itemstack.oncraft call. By using the method that I linked it would allow both mods to make the same change while being compatible. And it would reduce the amount of code you had to copy from vanilla.

I would be happy to make a PR to fix the issue if you would like. Thanks.

**Comment by MrMarnic** [comment]
Thank you. Will be changed.

**Comment by MrMarnic** [comment]
Fixed in v1.14.4 Fabric b3
