### ISSUE TITLE
Mixin failure on dedicated server

### ISSUE THREAD

**Issue by calloatti** [MrMarnic/AnimalNet#21]
`[main/WARN]: @Mixin target net.minecraft.class_1132 was not found animalnet.mixins.json:AnimalNetMixinServerStartingIntegrated`

https://paste.ee/p/nalIl

**Comment by calloatti** [comment]
~I suspect this may be related to #20~

Spawners can be crafted with spawner shards normally in my case.

**Comment by MrMarnic** [comment]
Fixed in v1.14.4 Fabric b3
