### ISSUE TITLE
[Fabric]animalData folder created outside save on Linux

### ISSUE THREAD

**Issue by Lartza** [MrMarnic/AnimalNet#25]
Your code that deals with animalData gets turned to world\animalData and on Linux that ends up creating a literal "world\animalData" folder outside the world folder.

Tested on a Fabric server using AnimalNet b4.

**Comment by MrMarnic** [comment]
Ok. Where is the folder created also the path

**Comment by Lartza** [comment]
Just on the root of the server, next to the world folder

**Comment by MrMarnic** [comment]
Can you test out this build please. Because I don't have Linux.
https://www.dropbox.com/s/k4a1vftbeejwtu2/animalnet-v1.14.4%20Fabric%20b5.jar?dl=1

**Comment by Lartza** [comment]
It does at least create the folder in the right place yes. Can't test if it works gameplay wise right now but I would assume it does if you use the path the same way each time.

**Comment by MrMarnic** [comment]
ok thank you. Then I will upload it and close this
