### ISSUE TITLE
Iron Golems

### ISSUE THREAD

**Issue by Anginator** [MrMarnic/AnimalNet#26]
on a server that i host, before we added the net mod, we had iron golems, but after installing the mod we don't have anything with iron golems, not the spawn egg or the recipe for one, the version we are using is 1.12.2 B2.  Thank you.

**Comment by MrMarnic** [comment]
How did you get a Iron Golem spawn egg before? Because the AnimalNet mod should not change any vanilla recipes

**Comment by Anginator** [comment]
In the list of the spawn eggs, its isn't showing its listed and when we try to make one it doesn't spawn, we checked in creative in the game for the spawn egg.

**Comment by Anginator** [comment]
After removing the mod, restarting the server, and installing again with another restart of the server it works just fine, it was apparently just a random glitch. sorry to have wasted your time.

**Comment by MrMarnic** [comment]
Ok no problem
