### ISSUE TITLE
[1.7 - MC-1.14 - Ubuntu 16.04] - Server crashing and stopping when trying to capture a mob

### ISSUE THREAD

**Issue by elhertz** [MrMarnic/AnimalNet#9]
**Minecraft Version:** 1.14 Mod Version: 1.7 ModLoaderVersion: Fabric 0.4.7+build.147

**Type:** Server

**Description:** I'm playing Minecraft 1.14 (Win10) on my Fabric server (Ubuntu 16.04) with these mods https://i.imgur.com/DDG9wl5.png
I've installed this version both in my pc and dedicated server: https://i.imgur.com/ZljNGdP.png
When I try to capture a mob I get kicked and my server crashes and restarts itself.

**Server log:** https://pastebin.com/H3YXV8B8

**Comment by MrMarnic** [comment]
Fixed in version "AnimalNet-1.8.1 Fabric 1.14"
